export const colors = {
  colorTitleBorderBottom: "#dddedf",
  colorStart: "#3e3e59",
  colorEnd: "#454573",
  colorBg: "#ffffff",
  colorCardWorkBg: "#ffffff",
  colorDarkText: "#a0a5b1",
  colorMostDarkText: "#414c63",
  colorBlackText: "#000000",
  colorText: "rgba(255,255,255,1)",
  colorDefaultIcon: "#a0a5b1",
  errorColor: "red",
  backgroundColorNav: "white",
  backgroundColorCard: "white",
  colorLinkHover: "#383bcf",
  colorShadow: "a0a5b1",
  colorAddBtnFirst: "#1459e2",
  colorAddBtnSecond: "#3f35cb",
  colorAddBtnThird: "#fff",
  bgImgContainer: "#dee4ed",
  colorRectBtnText: "#5558d6",
  colorRectBtnTextHover: "#ffffff",
  colorBtnOutline: "red",
  commonMostDarkColor: "#414c63",
  commonDarkColor: "#a0a5b1",
  commonLightColor: "#f4f4f4",
  commonOutlignColor: "#5558d6",
  commonLinkColor: "#383bcf",
  commonBgCardColor: "#ffffff",
  commonHeaderTitleText: "#ffffff",
  commonFillIconChange: "#383bcf",
  commonFillIconDelete: "#c92e2e",
  commonBgColor: "#ffffff",
  commonAuthButtonGradientStart: "#9300ef",
  commonAuthButtonGradientEnd: "#5500f2",
  commonEditingAccept: "#00d70a",
  commonEditingDecline: "#bf2929",
  commonColorLinkHover: "#383bcf",
  commonColorAddBtnFirst: "#1459e2",
  commonColorAddBtnSecond: "#3f35cb",
  commonColorAddBtnThird: "#fff",
  commonColorRectBtnText: "#5558d6",
  commonColorRectBtnTextHover: "#ffffff",
  commonErrorColor: "red",
  commonBackgroundColorNav: "white",
  commonColorShadow: "#a0a5b1",
  commonBackgroundColorCard: "white"
};

export const media = {
  phones: "768px",
  tablets: "1200px"
};
